<?php
/**
 * Pdfviewer.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Pdfviewer
 * @author Sascha Rösler <sa.roesler@st-marien-spandau.de>.
 * @link http://st-marien-spandau.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Jul 09 16:46:30 CEST 2013.
 */

/**
 * Installer base class.
 */
class Pdfviewer_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the Pdfviewer application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // Check if upload directories exist and if needed create them
        try {
            $controllerHelper = new Pdfviewer_Util_Controller($this->serviceManager);
            $result = $controllerHelper->checkAndCreateUploadFolder('document', 'datei', 'gif, jpeg, jpg, png, pdf, odt, doc');
            
        } catch (\Exception $e) {
            return LogUtil::registerError($e->getMessage());
        }
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->name));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        $categoryRegistryIdsPerEntity = array();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        //HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the Pdfviewer application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case 1.0.0:
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s extension.', array($this->getName())));
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall Pdfviewer.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s extension.', array($this->name)));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        //HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // remove all thumbnails
        $manager = $this->getServiceManager()->getService('systemplugin.imagine.manager');
        $manager->setModule($this->name);
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = FileUtil::getDataDirectory() . '/' . $this->name . '/';
        LogUtil::registerStatus($this->__f('The upload directories at [%s] can be removed manually.', $uploadPath));
    
        // deletion successful
        return true;
    }
    
    /**
     * Build array with all entity classes for Pdfviewer.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'Pdfviewer_Entity_Document';
    
        return $classNames;
    }
    
    /**
     * Create the default data for Pdfviewer.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids.
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'Pdfviewer_Entity_Document';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $dNow = date('Y-m-d');
        $document1 = new \Pdfviewer_Entity_Document();
        $document2 = new \Pdfviewer_Entity_Document();
        $document3 = new \Pdfviewer_Entity_Document();
        $document4 = new \Pdfviewer_Entity_Document();
        $document5 = new \Pdfviewer_Entity_Document();
        
        $document1->setWorkflowState('initial');
        $document1->setTitle('Document title 1');
        $document1->setBegindate($dNow);
        $document1->setEnddate($dNow);
        
        $document2->setWorkflowState('initial');
        $document2->setTitle('Document title 2');
        $document2->setBegindate($dNow);
        $document2->setEnddate($dNow);
        
        $document3->setWorkflowState('initial');
        $document3->setTitle('Document title 3');
        $document3->setBegindate($dNow);
        $document3->setEnddate($dNow);
        
        $document4->setWorkflowState('initial');
        $document4->setTitle('Document title 4');
        $document4->setBegindate($dNow);
        $document4->setEnddate($dNow);
        
        $document5->setWorkflowState('initial');
        $document5->setTitle('Document title 5');
        $document5->setBegindate($dNow);
        $document5->setEnddate($dNow);
        
        
        // execute the workflow action for each entity
        $action = 'submit';
        $workflowHelper = new Pdfviewer_Util_Workflow($this->serviceManager);
        try {
            $success = $workflowHelper->executeAction($document1, $action);
            $success = $workflowHelper->executeAction($document2, $action);
            $success = $workflowHelper->executeAction($document3, $action);
            $success = $workflowHelper->executeAction($document4, $action);
            $success = $workflowHelper->executeAction($document5, $action);
        } catch(\Exception $e) {
            LogUtil::registerError($this->__('Sorry, but an unknown error occured during example data creation. Possibly not all data could be created properly!'));
        }
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'api.method_not_found', array('Pdfviewer_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'core.preinit', array('Pdfviewer_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'core.init', array('Pdfviewer_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'core.postinit', array('Pdfviewer_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'controller.method_not_found', array('Pdfviewer_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> Pdfviewer_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'frontcontroller.predispatch', array('Pdfviewer_Listener_FrontController', 'preDispatch'));
    
        // installer -> Pdfviewer_Listener_Installer
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'installer.module.installed', array('Pdfviewer_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'installer.module.upgraded', array('Pdfviewer_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'installer.module.uninstalled', array('Pdfviewer_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'installer.subscriberarea.uninstalled', array('Pdfviewer_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> Pdfviewer_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module_dispatch.postloadgeneric', array('Pdfviewer_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module_dispatch.preexecute', array('Pdfviewer_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module_dispatch.postexecute', array('Pdfviewer_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module_dispatch.custom_classname', array('Pdfviewer_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module_dispatch.service_links', array('Pdfviewer_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> Pdfviewer_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.mailer.api.sendmessage', array('Pdfviewer_Listener_Mailer', 'sendMessage'));
    
        // page -> Pdfviewer_Listener_Page
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'pageutil.addvar_filter', array('Pdfviewer_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'system.outputfilter', array('Pdfviewer_Listener_Page', 'systemOutputfilter'));
    
        // errors -> Pdfviewer_Listener_Errors
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'setup.errorreporting', array('Pdfviewer_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'systemerror', array('Pdfviewer_Listener_Errors', 'systemError'));
    
        // theme -> Pdfviewer_Listener_Theme
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'theme.preinit', array('Pdfviewer_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'theme.init', array('Pdfviewer_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'theme.load_config', array('Pdfviewer_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'theme.prefetch', array('Pdfviewer_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'theme.postfetch', array('Pdfviewer_Listener_Theme', 'postFetch'));
    
        // view -> Pdfviewer_Listener_View
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'view.init', array('Pdfviewer_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'view.postfetch', array('Pdfviewer_Listener_View', 'postFetch'));
    
        // user login -> Pdfviewer_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.login.started', array('Pdfviewer_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.login.veto', array('Pdfviewer_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.login.succeeded', array('Pdfviewer_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.login.failed', array('Pdfviewer_Listener_UserLogin', 'failed'));
    
        // user logout -> Pdfviewer_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.logout.succeeded', array('Pdfviewer_Listener_UserLogout', 'succeeded'));
    
        // user -> Pdfviewer_Listener_User
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'user.gettheme', array('Pdfviewer_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'user.account.create', array('Pdfviewer_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'user.account.update', array('Pdfviewer_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'user.account.delete', array('Pdfviewer_Listener_User', 'delete'));
    
        // registration -> Pdfviewer_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.registration.started', array('Pdfviewer_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.registration.succeeded', array('Pdfviewer_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.ui.registration.failed', array('Pdfviewer_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'user.registration.create', array('Pdfviewer_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'user.registration.update', array('Pdfviewer_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'user.registration.delete', array('Pdfviewer_Listener_UserRegistration', 'delete'));
    
        // users module -> Pdfviewer_Listener_Users
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.users.config.updated', array('Pdfviewer_Listener_Users', 'configUpdated'));
    
        // group -> Pdfviewer_Listener_Group
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'group.create', array('Pdfviewer_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'group.update', array('Pdfviewer_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'group.delete', array('Pdfviewer_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'group.adduser', array('Pdfviewer_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'group.removeuser', array('Pdfviewer_Listener_Group', 'removeUser'));
    
        // special purposes and 3rd party api support -> Pdfviewer_Listener_ThirdParty
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'get.pending_content', array('Pdfviewer_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('Pdfviewer', 'module.content.gettypes', array('Pdfviewer_Listener_ThirdParty', 'contentGetTypes'));
    }
}
