<?php
/**
 * Pdfviewer.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Pdfviewer
 * @author Sascha Rösler <sa.roesler@st-marien-spandau.de>.
 * @link http://st-marien-spandau.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Jul 09 16:46:29 CEST 2013.
 */

/**
 * Version information base class.
 */
class Pdfviewer_Base_Version extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '1.0.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Pdfviewer');
        // the module description
        $meta['description']          = $this->__('Pdfviewer module generated by ModuleStudio 0.6.0.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('pdfviewer');
        // core requirement
        $meta['core_min']             = '1.3.5'; // requires minimum 1.3.5
        $meta['core_max']             = '1.3.5'; // not ready for 1.3.6 yet

        // define special capabilities of this module
        /*$meta['capabilities'] = array(
                          //HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => false)
/*,
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
                          'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')

        );*/

        // permission schema
        $meta['securityschema'] = array(
            'Pdfviewer::' => '::',
            'Pdfviewer::Ajax' => '::',
            'Pdfviewer:ItemListBlock:' => 'Block title::',
            'Pdfviewer:Document:' => 'Document ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
   /* protected function setupHookBundles()
    {
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.pdfviewer.ui_hooks.documents', 'ui_hooks', __('pdfviewer Documents Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'pdfviewer.ui_hooks.documents.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'pdfviewer.ui_hooks.documents.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'pdfviewer.ui_hooks.documents.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'pdfviewer.ui_hooks.documents.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'pdfviewer.ui_hooks.documents.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'pdfviewer.ui_hooks.documents.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'pdfviewer.ui_hooks.documents.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.pdfviewer.filter_hooks.documents', 'filter_hooks', __('pdfviewer Documents Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'pdfviewer.filter_hooks.documents.filter');
        $this->registerHookSubscriberBundle($bundle);

        
    }*/
}
