<?php
/**
 * Pdfviewer.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Pdfviewer
 * @author Sascha Rösler <sa.roesler@st-marien-spandau.de>.
 * @link http://st-marien-spandau.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Jul 09 16:46:30 CEST 2013.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for document entities.
 */
class Pdfviewer_Entity_Validator_Document extends Pdfviewer_Entity_Validator_Base_Document
{
    // here you can add custom validation methods or override existing checks
}
