<?php
/**
 * Pdfviewer.
 *
 * @copyright Sascha Rösler (SR)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Pdfviewer
 * @author Sascha Rösler <sa.roesler@st-marien-spandau.de>.
 * @link http://st-marien-spandau.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Tue Jul 09 16:46:30 CEST 2013.
 */

/**
 * This handler class handles the page events of the Form called by the pdfviewer_admin_edit() function.
 * It collects common functionality required by different object types.
 */
class Pdfviewer_Form_Handler_Admin_Edit extends Pdfviewer_Form_Handler_Admin_Base_Edit
{
    // feel free to extend the base handler class here
}
